#Please touch here only if you know what you're actually doing.
jars:
    Firebird: http://www.firebirdsql.org/en/jdbc-driver/
    FrontBase: http://www.frontbase.com/cgi-bin/WebObjects/FBWebSite
    DB2: http://www-01.ibm.com/support/docview.wss?uid=swg21363866
    Informix: http://www14.software.ibm.com/webapp/download/search.jsp?go=y&rs=ifxjdbc
    Ingres: http://esd.actian.com/product/drivers/JDBC/java
    MaxDB: ftp://ftp.sap.com/pub/sapdb/bin/java/sapdbc.jar
    MicrosoftSQL: http://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774
    Mongo: https://github.com/downloads/mongodb/mongo-java-driver/mongo-2.10.1.jar
    mSQL: http://www.hughes.com.au/download/index.ehtml?prod_name=Mini+SQL+3&prod_ver=Mini+SQL+3.11
    MySQL: http://dev.mysql.com/downloads/connector/j/
    Oracle: http://download.oracle.com/otn/utilities_drivers/jdbc/11203/simplefan.jar
    PostgreSQL: http://jdbc.postgresql.org/download/postgresql-9.2-1002.jdbc4.jar
    SQLite: http://www.xerial.org/maven/repository/artifact/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.jar
    H2: http://repo2.maven.org/maven2/com/h2database/h2/1.3.170/h2-1.3.170.jar
#Vote message to broadcast to all server
vote-message: '%player% voted at %service%'
#Please insert up to 9 links
links:
  material: SIGN
  name: 'Click me to see the voting links'
  data: 0
  lore: 'Here you can find all the voting links'
  1:
    name: MinecraftList
    #You can disable link so if you don't have up to 9 links you can insert a glass/decorative materials
    enable-link: true
    link: minecraftlist.tld
    material: SIGN
    lore: MinecraftList vote
    #It needs to be exactly the same as "outputted" by the vote-message
    service-name: 'Minecraft-List'
  2:
    name: ''
    enable-link: false
    material: STAINED_GLASS
    data: 2
    lore: 'Empty link slot'
    service-name: ''
  3:
    name: ''
    enable-link: false
    material: STAINED_GLASS
    data: 2
    lore: 'Zelda'
    service-name: ''
  4:
    name: ''
    enable-link: false
    material: STAINED_GLASS
    data: 2
    lore: 'love'
    service-name: ''
  5:
    name: ''
    enable-link: false
    material: STAINED_GLASS
    data: 2
    lore: 'kiss him'
    service-name: ''
  6:
    name: ''
    enable-link: false
    material: STAINED_GLASS
    data: 2
    lore: 'wife'
    service-name: ''
  7:
    name: ''
    enable-link: false
    material: STAINED_GLASS
    data: 2
    lore: 'memes'
    service-name: ''
  8:
    name: ''
    enable-link: false
    material: STAINED_GLASS
    data: 2
    lore: 'doge'
    service-name: ''
  9:
    name: ''
    enable-link: false
    material: STAINED_GLASS
    data: 2
    lore: 'potato'
    service-name: ''
#Below here, don't touch
waiting-list: []
waiting-numbers:
  - 'uuid;2;service;timestamp;xxx.xx.xxx.xx



